### ISSUE TITLE
new branches

### ISSUE THREAD

**Issue by kkellerlbl** [kbase/jars#17]
We should have develop and staging branches of the jars repo, to match the branches some repos already have, and others are moving to, to support the -ci and -next deployment environments.  Any objections?

**Comment by MrCreosote** [comment]
Why? Having different branches won't change anything. In order for a new 
jar to be used, another repo needs to add that jar to their build. 
Adding a jar to master without changes elsewhere does nothing.

-g

On 5/28/2015 2:43 PM, kkellerlbl wrote:
>
> We should have develop and staging branches of the jars repo, to match 
> the branches some repos already have, and others are moving to, to 
> support the -ci and -next deployment environments. Any objections?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/kbase/jars/issues/17>.
>



---
This email has been checked for viruses by Avast antivirus software.
http://www.avast.com

**Comment by kkellerlbl** [comment]
Yeah, Mike just reminded me that jars basically don't change once they're committed.  So we're all good.
